insert into Employees (empEmail, empName, empPhone#) values ('jshanahan0@biblegateway.com', 'Joy Shanahan', '973-398-8237');
insert into Employees (empEmail, empName, empPhone#) values ('estanlike1@multiply.com', 'Elayne Stanlike', '645-774-1800');
insert into Employees (empEmail, empName, empPhone#) values ('mchiswell2@google.cn', 'Mabel Chiswell', '918-912-1173');
insert into Employees (empEmail, empName, empPhone#) values ('bshirrell3@arstechnica.com', 'Britni Shirrell', '872-333-8997');
insert into Employees (empEmail, empName, empPhone#) values ('dglacken4@miibeian.gov.cn', 'Dionysus Glacken', '653-980-4293');
insert into Employees (empEmail, empName, empPhone#) values ('sphinnessy5@netscape.com', 'Saidee Phinnessy', '754-434-9566');
insert into Employees (empEmail, empName, empPhone#) values ('ifaulkner6@booking.com', 'Inessa Faulkner', '287-435-1903');
insert into Employees (empEmail, empName, empPhone#) values ('alippo7@fc2.com', 'Annette Lippo', '202-179-0402');
insert into Employees (empEmail, empName, empPhone#) values ('mkornes8@photobucket.com', 'Magdaia Kornes', '801-568-5157');
insert into Employees (empEmail, empName, empPhone#) values ('emose9@hugedomains.com', 'Etti Mose', '428-855-5252');
insert into Employees (empEmail, empName, empPhone#) values ('dfeldhammera@wordpress.org', 'Demetris Feldhammer', '803-140-9741');
insert into Employees (empEmail, empName, empPhone#) values ('lbozierb@unc.edu', 'Lise Bozier', '286-928-0036');
insert into Employees (empEmail, empName, empPhone#) values ('filiffec@nifty.com', 'Fay Iliffe', '659-256-9499');
insert into Employees (empEmail, empName, empPhone#) values ('dteresad@hc360.com', 'Drusie Teresa', '883-618-8858');
insert into Employees (empEmail, empName, empPhone#) values ('mgellione@ycombinator.com', 'Margalit Gellion', '371-697-0884');
insert into Employees (empEmail, empName, empPhone#) values ('tbrinef@buzzfeed.com', 'Taffy Brine', '369-868-8505');
insert into Employees (empEmail, empName, empPhone#) values ('fvang@columbia.edu', 'Faustine Van Bruggen', '916-521-6890');
insert into Employees (empEmail, empName, empPhone#) values ('mcalcrafth@reuters.com', 'Modestia Calcraft', '856-538-3392');
insert into Employees (empEmail, empName, empPhone#) values ('sdii@va.gov', 'Shaina Di Dello', '499-784-2067');
insert into Employees (empEmail, empName, empPhone#) values ('emagnusj@wordpress.org', 'Ella Magnus', '357-196-9130');
