insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('Harriton', 'Jerzees Zip Front Hoodie', 'Yellow', 'large', 5, 44.09);
insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('Gildan', 'Hanes Ladies ComfortSoft', 'Fuscia', 'medium', 15, 44.01);
insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('Next Level', 'Hanes Tagless T-Shirt', 'Violet', 'medium', 12, 49.22);
insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('Jerzees', 'Jerzees Zip Front Hoodie', 'Crimson', 'medium', 1, 32.45);
insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('Next Level', 'Jerzees Zip Front Hoodie', 'Mauv', 'x-small', 3, 31.07);
insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('Harriton', 'Fruit of the Loom Cotton', 'Fuscia', 'medium', 12, 49.43);
insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('American Apparel', 'Hanes Ladies ComfortSoft', 'Goldenrod', 'medium', 3, 44.81);
insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('American Apparel', 'Hanes Tagless T-Shirt', 'Maroon', 'small', 5, 31.04);
insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('Champion', 'Ultra Cotton Tank', 'Mauv', 'medium', 15, 49.02);
insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('American Apparel', 'Fruit of the Loom Cotton', 'Blue', 'x-large', 15, 37.6);
insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('American Apparel', 'Fruit of the Loom Cotton', 'Goldenrod', 'x-large', 1, 36.23);
insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('Jerzees', 'Fruit of the Loom Cotton', 'Violet', 'medium', 15, 47.8);
insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('Harriton', 'Hanes Ladies ComfortSoft', 'Mauv', 'large', 6, 15.58);
insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('Harriton', 'Hanes Tagless T-Shirt', 'Crimson', 'small', 13, 48.58);
insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('Jerzees', 'Hanes Ladies ComfortSoft', 'Indigo', 'x-small', 15, 42.6);
insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('Anvil', 'Fruit of the Loom Cotton', 'Fuscia', 'large', 4, 22.94);
insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('Gildan', 'Hanes Ladies ComfortSoft', 'Purple', 'medium', 15, 17.04);
insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('Anvil', 'Hanes Tagless T-Shirt', 'Violet', 'x-large', 13, 35.68);
insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('Harriton', 'Fruit of the Loom Cotton', 'Maroon', 'x-small', 7, 27.85);
insert into TShirts (tshBrand, tshName, tshColor, tshSize, tshAmount, tshPrice) values ('Jerzees', 'Canvas Unisex T-Shirt', 'Maroon', 'x-small', 1, 20.48);
